apiVersion: v2
appVersion: 11.0.11
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://repo.helmforge.dev
  version: 2.0.3
- condition: valkey.enabled
  name: valkey
  repository: https://repo.helmforge.dev
  version: 2.0.2
description: GLPI 11 (PHP-FPM + nginx + MariaDB + Valkey) on Kubernetes
name: myhelm
type: application
version: 0.2.10
