{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.mariadb.auth.existingSecret }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef: {name: {{ .Values.externalSecrets.secretStoreRef.name }}, kind: {{ .Values.externalSecrets.secretStoreRef.kind }}}
  target: {name: {{ .Values.mariadb.auth.existingSecret }}, creationPolicy: Owner}
  data:
    - {secretKey: mariadb-root-password, remoteRef: {key: {{ .Values.externalSecrets.remoteKey }}, property: mariadb-root-password}}
    - {secretKey: mariadb-user-password, remoteRef: {key: {{ .Values.externalSecrets.remoteKey }}, property: mariadb-user-password}}
    - {secretKey: mariadb-replication-password, remoteRef: {key: {{ .Values.externalSecrets.remoteKey }}, property: mariadb-replication-password}}
    - {secretKey: valkey-password, remoteRef: {key: {{ .Values.externalSecrets.remoteKey }}, property: valkey-password}}
{{- end }}