apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "MyHelm.fullname" . }}-glpi-config
data:
  GLPI_LANG: en_US
  GLPI_VAR_DIR: /var/lib/glpi
  GLPI_CONFIG_DIR: /etc/glpi/config
  GLPI_MARKETPLACE_DIR: /var/www/html/marketplace
  MARIADB_HOST: "{{ .Release.Name }}-mariadb"
  MARIADB_PORT: "3306"
  MARIADB_DATABASE: "{{ .Values.mariadb.auth.database }}"
  MARIADB_USER: "{{ .Values.mariadb.auth.username }}"
  