{{- if .Values.etcPersistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "MyHelm.fullname" . }}-etc
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "MyHelm.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml (.Values.etcPersistence.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  {{- with .Values.etcPersistence.storageClass }}
  storageClassName: {{ if eq . "-" }}{{ "" | quote }}{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
  resources: {requests: {storage: {{ .Values.etcPersistence.size }}}}
{{- end }}
---
{{- if .Values.filesPersistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "MyHelm.fullname" . }}-files
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "MyHelm.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml (.Values.filesPersistence.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  {{- with .Values.filesPersistence.storageClass }}
  storageClassName: {{ if eq . "-" }}{{ "" | quote }}{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
  resources: {requests: {storage: {{ .Values.filesPersistence.size }}}}
{{- end }}