{{- if .Values.marketplacePersistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "MyHelm.fullname" . }}-marketplace
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "MyHelm.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml (.Values.marketplacePersistence.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  {{- with .Values.marketplacePersistence.storageClass }}
  storageClassName: {{ if eq . "-" }}{{ "" | quote }}{{ else }}{{ . | quote }}{{ end }}
  {{- end }}
  resources: {requests: {storage: {{ .Values.marketplacePersistence.size }}}}
{{- end }}
