apiVersion: v1
kind: Service
metadata:
  name: {{ include "MyHelm.fullname" . }}
  labels:
    {{- include "MyHelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and .Values.nginx.service.nodePort (eq .Values.nginx.service.type "NodePort") }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
  selector:
    {{- include "MyHelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx