apiVersion: v1
kind: Service
metadata:
  name: {{ include "MyHelm.fullname" . }}-phpfpm
  labels:
    {{- include "MyHelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: php-fpm
spec:
  type: ClusterIP
  ports:
    - {port: 9000, targetPort: fpm, name: fpm}
  selector:
    {{- include "MyHelm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: php-fpm